---
sendgrid:
  from: <%= ENV['SG_FROM'] %>
  user: <%= ENV['SG_USER'] %>
  pass: <%= ENV['SG_KEY'] %>
  to:   <%= ENV['REVIEWER'] %>
  cc: dmitry.shmelev@onetwotrip.com
  subject: 'OTT-Infra: CodeReview'
bitbucket:
  username: 'anton.panov@onetwotrip.com'
  password: 'tQfpEHexNkxerSnfBqaN6F3E'
jira:
  username: 'anton.panov@onetwotrip.com'
  useremail: 'anton.panov@onetwotrip.com'
  password: 'tQfpEHexNkxerSnfBqaN6F3E'
  token: 'tQfpEHexNkxerSnfBqaN6F3E'
  site:     'https://onetwotripdev.atlassian.net'
  issue:    <%= ENV['ISSUE'] %>
  auth_type: :basic
  context_path: ''
  tags:
    field: 'customfield_11001'
    deploy: 'Manual Deploy'
  excluded_projects:
    - 'Hotels'
    - 'Servers & Services'
git:
  reviewer: <%= ENV['GITATTR_REVIEWER'] %>
  reviewer_key: <%= ENV.fetch('GITATTR_REVIEWER_KEY', 'reviewer.mail') %>
  workdir: <%= ENV.fetch('WORKDIR', './repos/') %>
test:
  npm:
    dryrun_for:
      - 'OneTwoTrip/xjsx'
