inherit_from: .rubocop_todo.yml
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
Metrics/LineLength:
  Enabled: true
  Max: 140
Metrics/MethodLength:
  Max: 12
AllCops:
  TargetRubyVersion: 2.1
  Exclude:
    - repos/**/*
    - vendor/**/*
