Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
Metrics/LineLength:
  Enabled: true
  Max: 140
Metrics/MethodLength:
  Max: 12
  Exclude:
    - lib/scenarios/*.rb
Metrics/ClassLength:
  Exclude:
    - lib/scenarios/*.rb
Metrics/AbcSize:
  Exclude:
    - lib/scenarios/*.rb
Metrics/CyclomaticComplexity:
  Exclude:
    - lib/scenarios/*.rb
Metrics/PerceivedComplexity:
  Exclude:
    - lib/scenarios/*.rb
AllCops:
  TargetRubyVersion: 2.1
  Exclude:
    - repos/**/*
    - vendor/**/*
